### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by RichardLWright** [breenmachine/httpscreenshot#31]
I am using httpscreenshot to see if sites are up and understanding what they are hosting. This list has 675 domains and I am using the --headless flag. The list of domains consist of sites that may or may not be hosting anything. Testing against 50 sites known to be hosting content the script works pretty well. When testing against a list of sites that might not be hosting anything it fails out with the following:

[-] Something bad happened with URL: <Domain>
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "../httpscreenshot.py", line 370, in worker
    browser.quit()
  File "/home/<user>/.local/lib/python2.7/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 80, in quit
    self.service.stop()
  File "/home/<user>/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 151, in stop
    self.send_remote_shutdown_command()
  File "/home/<user>/.local/lib/python2.7/site-packages/selenium/webdriver/phantomjs/service.py", line 67, in send_remote_shutdown_command
    os.close(self._cookie_temp_file_handle)
OSError: [Errno 9] Bad file descriptor

I've sought help on this error but can't get to a conclusion as to why this does not work. I'm trying to understand sites available to conduct further analysis on those hosting. Any help would be much appreciated.

Thanks.

**Comment by breenmachine** [comment]
Can you send me an example of a URL where it fails in this way?

**Comment by RichardLWright** [comment]
Here's a sample list that will fail out. I'm running this from a directory that I have created that contains the list so that all results will go inside that folder:

Command: sudo python ../httpscreenshot.py --list list --headless

http://googlezr.com
http://googlezs.com
http://googlezt.com
http://googlezu.com
http://googlezv.com
http://googlezw.com
http://googlezx.com
http://googlezy.com
http://googlezz.com
